[exec_bash_compare] Command to run:
python3 -m doctest ./tests/0-add_integer.txt
[exec_bash_compare] Return code: 1
[exec_bash_compare] Student stdout:
[exec_bash_compare] Student stdout length: 0
[exec_bash_compare] Student stderr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/usr/lib/python3.9/doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "/usr/lib/python3.9/doctest.py", line 2078, in testfile
    test = parser.get_doctest(text, globs, name, filename, 0)
  File "/usr/lib/python3.9/doctest.py", line 675, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/usr/lib/python3.9/doctest.py", line 689, in get_examples
    return [x for x in self.parse(string, name)
  File "/usr/lib/python3.9/doctest.py", line 651, in parse
    self._parse_example(m, name, lineno)
  File "/usr/lib/python3.9/doctest.py", line 709, in _parse_example
    self._check_prompt_
...318 more characters
[exec_bash_compare] Student stderr length: 1318
[exec_bash_compare] Desired stdout:
[exec_bash_compare] Desired stdout length: 0
[doctest_number_failed] Command to run:
python3 -m doctest  -v ./tests/0-add_integer.txt
[doctest_number_failed] Return code: 1
[doctest_number_failed] Student stdout:
[doctest_number_failed] Student stdout length: 0
[doctest_number_failed] Student stderr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/usr/lib/python3.9/doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "/usr/lib/python3.9/doctest.py", line 2078, in testfile
    test = parser.get_doctest(text, globs, name, filename, 0)
  File "/usr/lib/python3.9/doctest.py", line 675, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/usr/lib/python3.9/doctest.py", line 689, in get_examples
    return [x for x in self.parse(string, name)
  File "/usr/lib/python3.9/doctest.py", line 651, in parse
    self._parse_example(m, name, lineno)
  File "/usr/lib/python3.9/doctest.py", line 709, in _parse_example
    self._check_prompt_
...318 more characters
[doctest_number_failed] Student stderr length: 1318
[doctest_number_failed] Actual number of failed tests: 0
[doctest_number_passed] Command to run:
python3 -m doctest  -v ./tests/0-add_integer.txt
[doctest_number_passed] Return code: 1
[doctest_number_passed] Student stdout:
[doctest_number_passed] Student stdout length: 0
[doctest_number_passed] Student stderr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/usr/lib/python3.9/doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "/usr/lib/python3.9/doctest.py", line 2078, in testfile
    test = parser.get_doctest(text, globs, name, filename, 0)
  File "/usr/lib/python3.9/doctest.py", line 675, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/usr/lib/python3.9/doctest.py", line 689, in get_examples
    return [x for x in self.parse(string, name)
  File "/usr/lib/python3.9/doctest.py", line 651, in parse
    self._parse_example(m, name, lineno)
  File "/usr/lib/python3.9/doctest.py", line 709, in _parse_example
    self._check_prompt_
...318 more characters
[doctest_number_passed] Student stderr length: 1318
[doctest_number_passed] Return code: 1
[doctest_number_passed] Actual number of passed tests: 0
[doctest_number_passed] Actual stdout:
[doctest_number_passed] Actual stdout length: 0
[doctest_number_passed] Actual stderr:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "/usr/lib/python3.9/doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "/usr/lib/python3.9/doctest.py", line 2078, in testfile
    test = parser.get_doctest(text, globs, name, filename, 0)
  File "/usr/lib/python3.9/doctest.py", line 675, in get_doctest
    return DocTest(self.get_examples(string, name), globs,
  File "/usr/lib/python3.9/doctest.py", line 689, in get_examples
    return [x for x in self.parse(string, name)
  File "/usr/lib/python3.9/doctest.py", line 651, in parse
    self._parse_example(m, name, lineno)
  File "/usr/lib/python3.9/doctest.py", line 709, in _parse_example
    self._check_prompt_
...318 more characters
[doctest_number_passed] Actual stderr length: 1318